// packages/svelte-components/src/lib/Avatar.svelte
<script lang="ts">
    import type { IUser } from '@giphy/js-types'
    export let user: IUser
    const avatar = user.avatar_url
    let src: string
    if (avatar) {
        const ext = avatar?.split('.')?.pop()?.toLowerCase()
        src = avatar.replace(`.${ext}`, `/80h.${ext}`)
    } else {
        const id = Math.floor(Math.random() * 5) + 1
        src = `https://media.giphy.com/avatars/default${id}.gif`
    }
</script>

<img {src} alt={`${user.display_name}'s profile`} />

<style>
    img {
        object-fit: cover;
        width: 32px;
        height: 32px;
        margin-right: 8px;
    }
</style>

// packages/react-components/src/components/attribution/avatar.tsx
import { css, cx } from 'emotion'
import React from 'react'
import { IUser } from '@giphy/js-types'

const getSmallAvatar = (avatar: string) => {
    if (!avatar) return ''
    const ext = avatar
        ?.split('.')
        ?.pop()
        ?.toLowerCase()
    return avatar.replace(`.${ext}`, `/80h.${ext}`)
}

const avatarCss = css`
    object-fit: cover;
    width: 36px;
    height: 36px;
    margin-right: 8px;
`
type Props = { user: IUser; className?: string }
const Avatar = ({ user, className = '' }: Props) => {
    const url = user.avatar_url
        ? getSmallAvatar(user.avatar_url)
        : `https://media.giphy.com/avatars/default${Math.floor(Math.random() * 5) + 1}.gif`
    return <img src={url} className={cx(avatarCss, className)} />
}

export default Avatar
