// packages/svelte-components/src/routes/carousel/+page.svelte
<script lang="ts">
    import { GiphyFetch, type GifsResult } from '@giphy/js-fetch-api'
    import Carousel from '../../lib/Carousel.svelte'
    const gf = new GiphyFetch('sXpGFDGZs0Dv1mmNFvYaGUvYwKX0PWIh')
    const limit = 10
    /** @type {import('./$types').PageData} */
    export let data: GifsResult
</script>

<h1>Carousel</h1>
<Carousel initialGifs={data.data} gifHeight={100} fetchGifs={(offset) => gf.trending({ offset, limit })} />

<h1>Fixed gif width</h1>
<Carousel initialGifs={data.data} gifHeight={100} fetchGifs={(offset) => gf.trending({ offset, limit })} />

// packages/react-components/public/carousel.tsx
import { Carousel } from '../src'
import { IGif } from '@giphy/js-types'
import React, { PureComponent } from 'react'
import { GiphyFetch } from '@giphy/js-fetch-api'

const gf = new GiphyFetch('sXpGFDGZs0Dv1mmNFvYaGUvYwKX0PWIh')
const fetchGifs = (offset: number) => gf.trending({ offset, limit: 4 })

type State = {
    gifs: IGif[]
}
type Props = {}
class CarouselShowcase extends PureComponent<Props, State> {
    render() {
        return <Carousel gifHeight={200} user={{}} gutter={6} fetchGifs={fetchGifs} />
    }
}

export default CarouselShowcase
