// packages/svelte-components/src/lib/Attribution.svelte
<script lang="ts">
    import type { IGif, IProfileUser } from '@giphy/js-types'
    import Avatar from './Avatar.svelte'
    export let gif: IGif
    let shouldDisplay = true
    const user = gif.user as IProfileUser
    if (!user?.username && !user?.display_name) {
        shouldDisplay = false
    }
</script>

{#if shouldDisplay}
    <div
        class="container"
        on:click|preventDefault|stopPropagation={() => {
            if (user.profile_url) {
                window.open(user.profile_url, '_blank')
            }
        }}
        on:keydown={() => {}}
    >
        <Avatar {user} />
        <div class="user">{user.display_name || user.username}</div>
    </div>
{/if}

<style>
    .container {
        display: flex;
        align-items: center;
        font-family: interface, helvetica, arial;
        cursor: pointer;
    }
    .user {
        color: white;
        font-size: 16px;
        font-weight: 700;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
        -webkit-font-smoothing: antialiased;
    }
</style>

// packages/react-components/src/components/video/attribution.tsx
import { IGif, IProfileUser } from '@giphy/js-types'
import React from 'react'
import styled from 'styled-components'
import Avatar_ from '../attribution/avatar'
import User from '../attribution/user'
import GIPHYClips from './clips-branding'

const Container = styled.div`
    display: flex;
    align-items: center;
    font-family: interface, helvetica, arial;
    cursor: pointer;
`
const Avatar = styled(Avatar_)`
    flex-shrink: 0;
`
const Right = styled.div`
    display: flex;
    flex-direction: column;
`
type Props = { gif: IGif; className?: string; onClick?: (gif: IGif) => void }
const Attribution = ({ gif, className, onClick }: Props) => {
    const { user } = gif
    if (!user?.username && !user?.display_name) {
        return null
    }
    return (
        <Container
            className={[Attribution.className, className].join(' ')}
            onClick={(e) => {
                e.preventDefault()
                e.stopPropagation()
                if (onClick) {
                    onClick(gif)
                } else {
                    const url = (user as IProfileUser).profile_url
                    if (url) window.open(url, '_blank')
                }
            }}
        >
            <Avatar user={user} />
            <Right>
                <GIPHYClips
                    onClick={(e) => {
                        e.preventDefault()
                        e.stopPropagation()
                        if (onClick) {
                            onClick(gif)
                        } else if (gif.url) {
                            window.open(gif.url, '_blank')
                        }
                    }}
                />
                <User user={user} />
            </Right>
        </Container>
    )
}
Attribution.className = 'giphy-attribution'
export default Attribution
