// packages/svelte-components/src/lib/Carousel.svelte
<script lang="ts">
    import { gifPaginator, type GifsResult } from '@giphy/js-fetch-api'
    import type { IGif } from '@giphy/js-types'
    import { getGifWidth } from '@giphy/js-util'
    import { onMount } from 'svelte'
    import { debounce } from 'throttle-debounce'
    import Gif from './Gif.svelte'

    // if we have gifs we can pass them in as initialGifs
    export let initialGifs: IGif[] = []
    // we'll fetch extra gifs when the loader is visible
    export let fetchGifs: (offset: number) => Promise<GifsResult>
    // loader config lets us trigger a fetch before the user reaches the bottom
    export let loaderConfig = { rootMargin: '0px 0px 250px 0px' }
    export let gifHeight = 100
    export let gifWidth: number | undefined = undefined

    let isLoaderVisible = false
    let isFetching = false

    const paginator = gifPaginator(fetchGifs, initialGifs)
    const doFetch = debounce(100, async () => {
        if (isLoaderVisible && !isFetching) {
            isFetching = true
            const gifs = await paginator()
            initialGifs = gifs
            isFetching = false
        }
    })

    // when these change fetch more gifs
    $: initialGifs, isLoaderVisible, isFetching, doFetch()

    let loader: HTMLDivElement
    onMount(() => {
        const i = new IntersectionObserver(([entry]: IntersectionObserverEntry[]) => {
            isLoaderVisible = entry.isIntersecting
        }, loaderConfig)
        i.observe(loader)
        return () => i.disconnect()
    })
</script>

<div class="container">
    {#each initialGifs as gif}
        <div class="gif">
            <Gif {gif} width={gifWidth || getGifWidth(gif, gifHeight)} height={gifHeight} />
        </div>
    {/each}
    <div bind:this={loader} class="loader" />
</div>

<style>
    .gif {
        position: relative;
        display: inline-block;
        list-style: none;
        margin-left: 4px;
        /* make sure gifs are fully visible with a scrollbar */
        margin-bottom: 1px;
    }
    .gif:first-of-type {
        margin-left: 0;
    }
    .container {
        -webkit-overflow-scrolling: touch;
        overflow-x: auto;
        overflow-y: hidden;
        white-space: nowrap;
        position: relative;
    }
    .loader {
        display: inline-block;
        width: 50px;
        height: 50px;
    }
</style>

// packages/components/src/components/carousel.tsx
import { gifPaginator, GifsResult } from '@giphy/js-fetch-api'
import { IGif, IUser } from '@giphy/js-types'
import { getGifWidth } from '@giphy/js-util'
import { css, cx } from 'emotion'
import { Component, h, JSX } from 'preact'
import { debounce } from 'throttle-debounce'
import Observer from '../util/observer'
import Gif, { EventProps } from './gif'

const carouselCss = css`
    -webkit-overflow-scrolling: touch;
    overflow-x: auto;
    overflow-y: hidden;
    white-space: nowrap;
    position: relative;
`
const carouselItemCss = css`
    display: inline-block;
    list-style: none;
    /* make sure gifs are fully visible with a scrollbar */
    margin-bottom: 1px;
    &:first-of-type {
        margin-left: 0;
    }
`

const loaderContainerCss = css`
    display: inline-block;
`

const loaderCss = css`
    width: 30px;
    display: inline-block;
`

type Props = {
    className?: string
    user: Partial<IUser>
    gifHeight: number
    gutter: number
    fetchGifs: (offset: number) => Promise<GifsResult>
    onGifsFetched?: (gifs: IGif[]) => void
    noResultsMessage?: string | JSX.Element
} & EventProps

const defaultProps = Object.freeze({ gutter: 6, user: {} })

type State = {
    isFetching: boolean
    numberOfGifs: number
    gifs: IGif[]
    isLoaderVisible: boolean
    isDoneFetching: boolean
}
const initialState = Object.freeze({
    isFetching: false,
    numberOfGifs: 0,
    gifs: [] as IGif[],
    isLoaderVisible: true,
    isDoneFetching: false,
})

class Carousel extends Component<Props, State> {
    static className = 'giphy-carousel'
    static readonly defaultProps = defaultProps
    readonly state = initialState
    el?: HTMLElement
    paginator = gifPaginator(this.props.fetchGifs)
    componentDidMount() {
        this.onFetch()
    }

    onLoaderVisible = (isVisible: boolean) => {
        this.setState({ isLoaderVisible: isVisible }, this.onFetch)
    }

    onFetch = debounce(100, async () => {
        const { isFetching, isLoaderVisible, gifs: existingGifs } = this.state
        if (!isFetching && isLoaderVisible) {
            this.setState({ isFetching: true })
            let gifs
            try {
                gifs = await this.paginator()
            } catch (error) {
                this.setState({ isFetching: false })
            }
            if (gifs) {
                if (existingGifs.length === gifs.length) {
                    this.setState({ isDoneFetching: true })
                } else {
                    this.setState({ gifs, isFetching: false })
                    const { onGifsFetched } = this.props
                    if (onGifsFetched) onGifsFetched(gifs)
                    this.onFetch()
                }
            }
        }
    })

    render(
        {
            fetchGifs,
            onGifVisible,
            onGifRightClick,
            gifHeight,
            gutter,
            className = Carousel.className,
            onGifClick,
            onGifHover,
            onGifSeen,
            user,
            noResultsMessage,
        }: Props,
        { gifs }: State
    ) {
        const showLoader = fetchGifs && gifs.length > 0
        const marginCss = css`
            margin-left: ${gutter}px;
        `
        const gifHeightCss = css`
            height: ${gifHeight}px;
        `
        const containerCss = cx(className, carouselCss)
        const gifCss = cx(carouselItemCss, marginCss)
        return (
            <div class={containerCss}>
                {gifs.map(gif => {
                    const gifWidth = getGifWidth(gif, gifHeight)
                    return (
                        <Gif
                            className={gifCss}
                            gif={gif}
                            key={gif.id}
                            width={gifWidth}
                            onGifClick={onGifClick}
                            onGifHover={onGifHover}
                            onGifSeen={onGifSeen}
                            onGifVisible={onGifVisible}
                            onGifRightClick={onGifRightClick}
                            user={user}
                        />
                    )
                })}
                {!showLoader && gifs.length === 0 && noResultsMessage}
                {showLoader && (
                    <Observer className={loaderContainerCss} onVisibleChange={this.onLoaderVisible}>
                        <div className={cx(loaderCss, gifHeightCss)} />
                    </Observer>
                )}
            </div>
        )
    }
}

export default Carousel
